
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(here::here("InitializeProject.R"))
library(magrittr)
library(tidyverse)
```

```{r create_dds_GSE128682}
library(DESeq2)
library(org.Hs.eg.db)

# define the database
database <- org.Hs.eg.db

# extract the feature annotation

rowData <- AnnotationDbi::select(database,
# change according to database and desired information. Available columns can be queried with the columns(database) command
                                     columns = c("ENSEMBL", 
                                                 "ENTREZID", 
                                                 "SYMBOL", 
                                                 "GENENAME"),
# if using different featureIDs, such as SYMBOL, ENTREZ or so, change accordingly
                                           keys = keys(database, 
                                                       keytype = "SYMBOL"),
                                           keytype = "SYMBOL") %>%
  mutate(FEATUREID = SYMBOL) %>%
# End of necessary changes
  group_by(FEATUREID) %>%
  summarize_all(function(x){paste(unique(x), collapse = ", ")}) %>%
  mutate(rowname = FEATUREID) %>%
  column_to_rownames

# define the accession for further use
accession <- "GSE128682"

# read the counts matrix
counts <- rio::import(here::here(datadir, accession, "GSE128682_raw_counts.tsv")) %>%
  column_to_rownames("V1")

# the smple annotation is extracted from the sample names
colData <- data.frame(SAMPLEID = colnames(counts)) %>%
  mutate(STATUS = case_when(str_detect(SAMPLEID, "N_") ~ "normal",
                            str_detect(SAMPLEID, "UC_") ~ "diseased",
                            str_detect(SAMPLEID, "R_") ~ "remission",
                            TRUE ~ "unknown"),
         rowname = SAMPLEID) %>%
  mutate(STATUS = factor(STATUS, levels = c("normal", "diseased", "remission"))) %>%
  column_to_rownames()

# determin features that can be annotated
selected_features <- intersect(rownames(counts), rownames(rowData))

# construct a DESeq2 object
dds <- DESeqDataSetFromMatrix(countData = counts[selected_features,],
                              colData = colData,
                              design = ~STATUS)

# annotate the features
rowData(dds) <- rowData[selected_features,]


# save the dds object for further use
dds %>%
  rio::export(here::here(datadir, paste(accession, "dds.RDS", sep = "_")))
```

```{r PCA_GSE128682}
library(DESeq2)
library(PCAtools)
# define the accession number and load the DESeq2 object
accession <- "GSE128682"
dds <- rio::import(here::here(datadir, paste0(accession, "_dds.RDS")),
                   trust = TRUE)

# filter lowly abundant genes (less than 10 counts over all samples)
keep <- rowSums(counts(dds)) >= 10
dds_filtered <- dds[keep,]

# estimate dispersions and do a variance stabilizing transformation
dds_vst <- dds_filtered %>%
  DESeq() %>%
  vst

# extract the vst matrix
vst <- dds_vst %>%
  assay

# conduct a PCA
p <- pca(vst, 
         metadata = colData(dds_vst), 
         removeVar = 0.1)

# draw a biplot, coloration status
biplot <- biplot(p,
                 colby = "STATUS",
                 max.overlaps = 30,
                 encircle = TRUE)

# save the biplot for figure construction
biplot %>%
  ggsave(filename = here::here(plotsdir, paste0(accession, "_PCA.pdf")))
```

```{r DEGs_GSE128682}
library(DESeq2)

# define the accession number and load the DESeq2 object
accession <- "GSE128682"
dds <- rio::import(here::here(datadir, paste0(accession, "_dds.RDS")),
                   trust = TRUE)

# filter lowly abundant genes (less than 10 counts over all samples)
keep <- rowSums(counts(dds)) >= 10
dds_filtered <- dds[keep,]

# filter for uncharacterized loci
filter <- !(str_detect(rowData(dds_filtered)$GENENAME, "uncharacterized") |
              str_detect(rowData(dds_filtered)$GENENAME, "pseudogene") |
              str_detect(rowData(dds_filtered)$GENENAME, "non-protein coding"))
dds_filtered <- dds_filtered[filter,]

# additional filtering setp, here deactivated, therefore dds_filtered <- dds
dds_filtered <- dds_filtered %>%
  DESeq

# extract the feature annotation
rowData <- rowData(dds_filtered) %>%
  data.frame %>%
  dplyr::select(SYMBOL, ENTREZID, ENSEMBL, GENENAME)

# define the contrast list
contrast_list <- list(diseased_vs_normal = c("STATUS", "diseased", "normal"),
                      remission_vs_normal = c("STATUS", "remission", "normal"),
                      diseased_vs_remission = c("STATUS", "diseased", "remission"))

# fit model and determin the results
results <- contrast_list %>%
  purrr::map(function(contrast, dds, rowData){
    DESeq2::results(dds, contrast = contrast) %>%
      data.frame %>%
      rownames_to_column("SYMBOL") %>%
      inner_join(rowData) %>%
      dplyr::select(SYMBOL, ENTREZID, ENSEMBL, GENENAME, everything())
  },
  dds = dds_filtered,
  rowData = rowData)

# save results in an RDS object and an excel file
results %T>%
  rio::export(here::here(resultsdir, paste(accession, "DESeq2.RDS", sep = "_"))) %>%
  rio::export(here::here(resultsdir, paste(accession, "DESeq2.xlsx", sep = "_")))
```

```{r GSVA_GSE128682}
library(DESeq2)
library(GSVA)
library(Biobase)


# define the accession number and load the DESeq2 object
accession <- "GSE128682"
dds <- rio::import(here::here(datadir, paste0(accession, "_dds.RDS")),
                   trust = TRUE)

# filter lowly abundant genes (less than 10 counts over all samples)
keep <- rowSums(counts(dds)) >= 10
dds_filtered <- dds[keep,]

# filter for uncharacterized loci
filter <- !(str_detect(rowData(dds_filtered)$GENENAME, "uncharacterized") |
              str_detect(rowData(dds_filtered)$GENENAME, "pseudogene") |
              str_detect(rowData(dds_filtered)$GENENAME, "non-protein coding"))
dds_filtered <- dds_filtered[filter,]


# extract counts
assayData <- dds_filtered %>%
  counts

# extract sample annotation
phenoData <- colData(dds_filtered) %>%
  data.frame %>%
  AnnotatedDataFrame()

# create genesets
msigdb <- msigdbr::msigdbr(species = "Homo sapiens")

# define the term to gene association
term2gene <- msigdb %>%
  dplyr::select(gs_id, gene_symbol) %>%
  tidyr::nest(gg = -"gs_id") %>%
  deframe %>%
  purrr::map(deframe)

# define the term to name association
term2name <- msigdb %>%
  dplyr::select(gs_id, gs_cat, gs_subcat, gs_name, gs_exact_source) %>%
  distinct %>%
  mutate(rowname = gs_id) %>%
  column_to_rownames

# construct an expression set for further use in LIMMA
eset <- ExpressionSet(assayData = assayData,
                      phenoData = phenoData)


# set the gsva parameters
gsva_params <- gsvaParam(exprData = eset,
                         kcdf = "Poisson",
                         geneSets = term2gene)

# do the GSVA transformation
gsva <- gsva(gsva_params,
             BPPARAM = BiocParallel::MulticoreParam(workers = 10))

# annotate the features of teh´´he GSVA result
fData(gsva) <- term2name[featureNames(gsva),]

# save the result for later
gsva %>%
  rio::export(here::here(datadir, paste(accession, "gsva.RDS", sep = "_")))
```

```{r LIMMA_GSVA_GSE128682}
library(limma)
library(Biobase)

# define accession and load the GSVA eset
accession <- "GSE128682"

gsva <- rio::import(here::here(datadir, paste(accession, "gsva.RDS", sep = "_")),
                    trust = TRUE)

# define categories of interest
subcats_of_interest <- c(C5 = "GO:BP",
                         C2 = "CP:WIKIPATHWAYS")

# filter the gsva eset and split it into a list, each for one category of interest.
gsva_filtered <- subcats_of_interest %>%
  purrr::map(function(subcat, gsva){
    gsva[fData(gsva)$gs_subcat == subcat,]
  },
  gsva = gsva)

# define differentially enriched terms by LIMMA
results <- gsva_filtered %>%
  purrr::map(function(gsva){
    
    # define the model matrix
    design <- model.matrix(~0 + STATUS,
                           data = gsva)
    # define the contrasts
    contrast_list <- list(diseased_vs_normal = "STATUSdiseased - STATUSnormal",
                          remission_vs_normal = "STATUSremission - STATUSnormal",
                          diseased_vs_remission = "STATUSdiseased - STATUSremission")
    # construct a contrast matrix
    contrast_matrix <- makeContrasts(contrasts = contrast_list,
                                     levels = design) %>%
      set_colnames(names(contrast_list))
    # fit the model to the contrasts
    fit <- gsva %>%
      lmFit(design) %>%
      contrasts.fit(contrast_matrix) %>%
      eBayes
    
    # extract the coefficients
    coefs <- fit %>%
      coefficients() %>%
      colnames %>%
      set_names(.,.)
    
    # extract the results
    results <- coefs %>%
      purrr::map(function(coef, fit){
        topTable(fit, 
                 coef = coef, 
                 number = Inf) %>%
          data.frame
        },
        fit = fit)
    }) %>%
  unlist(recursive = FALSE)

# save results for later
results  %T>%
  rio::export(here::here(resultsdir, paste(accession, "LIMMA_GSVA.RDS", sep = "_"))) %>%
  rio::export(here::here(resultsdir, paste(accession, "LIMMA_GSVA.xlsx", sep = "_")))
  
```


```{r clusterProfiler_GSE128682}
library(clusterProfiler)

# load accession and differentially expressed genes
accession <- "GSE128682"

DEGs <- rio::import(here::here(resultsdir, paste(accession, "DESeq2.RDS", sep = "_")),
                    trust = TRUE) 

# set the threshold for the adjusted p value
threshold <- 0.05

# filter the DEG result
DEGs_filtered <- DEGs %>%
  purrr::map(function(df, thershold){
    df %>%
      dplyr::filter(padj < 0.05) %>%
      dplyr::select(ENTREZID) %>%
      deframe
  })

# construct the universe, i.e. all genes
universes <- DEGs %>%
  purrr::map(function(df){
    df %>%
      dplyr::select(ENTREZID) %>%
      deframe
  })

# query the molecular signature database
msigdb <- msigdbr::msigdbr(species = "Homo sapiens")

# filter for GO:BP and Wikipathways and split in categories
msigdb_filtered <- msigdb %>%
  dplyr::filter(gs_subcat == "GO:BP" | gs_subcat == "CP:WIKIPATHWAYS") %>%
  tidyr::nest(gg = -"gs_cat") %>%
  deframe

# construct the term2gene dataframe, one for each category
term2gene <- msigdb_filtered %>%
  purrr::map(function(df){
    df %>%
       dplyr::select(gs_id, entrez_gene)
  })
 
# construct the term 2 name mapping
term2name <- msigdb %>%
  dplyr::select(gs_id, gs_name) %>%
  distinct %>%
  mutate(rowname = gs_id) %>%
  column_to_rownames

# do the enrichment analysis for each term to gene and each contrast
results <- DEGs_filtered %>%
  purrr::map2(universes, 
              function(gene, universe, term2gene, term2name){
                term2gene %>%
                  purrr::map(function(term2gene, gene, universe, term2name){
                    enricher(gene = gene,
                             pvalueCutoff = 1,
                             qvalueCutoff = 1,
                             universe = universe,
                             TERM2GENE = term2gene,
                             TERM2NAME = term2name)
                  },
                  gene = gene,
                  universe = universe,
                  term2name = term2name)
    
  },
  term2gene = term2gene,
  term2name = term2name) %>%
  unlist(recursive = FALSE)

# save results for later
results %T>%
  rio::export(here::here(resultsdir, paste(accession, "clusterProfiler.RDS", sep = "_"))) %>%
  purrr::map(data.frame) %>%
  rio::export(here::here(resultsdir, paste(accession, "clusterProfiler.xlsx", sep = "_")))

```


```{r WGCNA_GSE128682}
library(DESeq2)
library(WGCNA)

# enable multithreading
enableWGCNAThreads(10)
options(stringsAsFactors = FALSE)

# define accession and load data
accession <- "GSE128682"
dds <- rio::import(here::here(datadir, paste0(accession, "_dds.RDS")),
                   trust = TRUE)

# filter lowly abundant genes (less than 10 counts over all samples)
keep <- rowSums(counts(dds)) >= 10
dds_filtered <- dds[keep,]

# filter for uncharacterized loci
filter <- !(str_detect(rowData(dds_filtered)$GENENAME, "uncharacterized") |
              str_detect(rowData(dds_filtered)$GENENAME, "pseudogene") |
              str_detect(rowData(dds_filtered)$GENENAME, "non-protein coding"))
dds_filtered <- dds_filtered[filter,]


# additional filtering setp, here deactivated, therefore dds_filtered <- dds
dds_filtered <- dds_filtered %>%
  DESeq

# do vst transformation
dds_vst <- dds_filtered %>%
  vst

# extract the vst matrix and transpose it
datExpr <- dds_vst %>%
  assay %>%
  t

# define the params for WGCNA
params <- list(networkType = "unsigned",
               corType = "pearson",
               maxBlockSize = 30000,
               # TOMType = "signed",
               minModuleSize = 30,
               reassignThreshold = 1e-6,
               detectCutHeight = 0.975,
               mergeCutHeight = 0.15,
               deepSplit = 2,
               numericLabels = TRUE,
               pamStage = FALSE,
               pamRespectsDendro = TRUE,
               verbose = 6,
               datExpr = datExpr)

# define the optimal beta
powers = c(seq(1,10,by=1), seq(12,20, by=2));
sft = pickSoftThreshold(params$datExpr,
                        corFnc = cor,
                        RsquaredCut = 0.8,
                        powerVector=powers,
                        networkType = params$networkType,
                        verbose = 6)

beta <- sft$powerEstimate
if (is.na(beta)){
  if (params$networkType == "unsigned"){
    beta <- 6
  } else {
    beta <- 12
  }
}

collectGarbage()
params$power <- beta

# do the WGCNA using blockwiseModules
net <- do.call(blockwiseModules, c(params))

# attach the underlying parameters and data
net$params <- as.list(args(blockwiseModules))
net$params[names(params)] <- params
net$dds <- dds
# save the net object and we are finished
net %>%
  rio::export(here::here(datadir, paste(accession, "net", "RDS", sep = ".")))
```

```{r biologic_context_GSE128682_WGCNA}
library(clusterProfiler)


# get the network and the data
accession <- "GSE128682"

net <- rio::import(here::here(datadir, paste(accession, "net", "RDS", sep = ".")),
                   trust = TRUE)

# extract the modules
modules <- data.frame(module = net$colors,
                      SYMBOL = colnames(net$params$datExpr)) %>%
  dplyr::filter(module != 0) %>%
  dplyr::mutate(module = paste0("M", module)) %>%
  tidyr::nest(gg = -"module") %>%
  deframe %>%
  purrr::map(deframe)

# extract the universe
universe <- colnames(net$params$datExpr)

# query the molecular signature database
msigdb <- msigdbr::msigdbr(species = "Homo sapiens")

# filter the molecular signature database
msigdb_filtered <- msigdb %>%
  dplyr::filter(gs_subcat == "GO:BP" | gs_subcat == "CP:WIKIPATHWAYS") %>%
  tidyr::nest(gg = -"gs_cat") %>%
  deframe

# construct a term2gene object list, one element per category
term2gene <- msigdb_filtered %>%
  purrr::map(function(df){
    df %>%
       dplyr::select(gs_id, gene_symbol)
  })

 
# extract the term annotation
term2name <- msigdb %>%
  dplyr::select(gs_id, gs_name) %>%
  distinct %>%
  mutate(rowname = gs_id) %>%
  column_to_rownames

# prepare multithreading
future::plan("multisession", 
             workers = 2)

# do the enrichment analysis for each module and each category
results <- modules %>%
  furrr::future_map(function(gene, universe, term2gene, term2name){
                term2gene %>%
                  purrr::map(function(term2gene, gene, universe, term2name){
                    enricher(gene = gene,
                             pvalueCutoff = 1,
                             qvalueCutoff = 1,
                             universe = universe,
                             TERM2GENE = term2gene,
                             TERM2NAME = term2name)
                  },
                  gene = gene,
                  universe = universe,
                  term2name = term2name)
    
  },
  term2gene = term2gene,
  term2name = term2name,
  universe = universe) %>%
  # flatten the list to one level
  unlist(recursive = FALSE)

# save for later
results %T>%
  rio::export(here::here(resultsdir, "modulecontext.RDS")) %>%
  purrr::map(data.frame) %>%
  rio::export(here::here(resultsdir, "modulecontext.xlsx")) 
```

```{r associate_modules_and_traits}
library(tidyverse)
library(magrittr)
library(DESeq2)
library(WGCNA)
library(Biobase)
library(cowplot)
library(scales)
library(mdthemes)

unicode_minus <- function(x){
  sub('^-', '\U2212', format(x))
}

scientific_10 <- function(x) {
  x %>%
    purrr::map_chr(function(x){
      gsub("e", " %*% 10^", scales::scientific_format()(x))
    })
}


# get the network and the data
accession <- "GSE128682"

net <- rio::import(here::here(datadir, paste(accession, "net", "RDS", sep = ".")),
                   trust = TRUE)

# extract the modules
moduleColors = paste("M", net$colors, sep = "")
nSamples <- nrow(net$params$datExpr)

# Recalculate MEs with color labels
MEs <- WGCNA::moduleEigengenes(net$params$datExpr, moduleColors)$eigengenes %>%
  dplyr::select(!matches("MEgrey"))

# extract the sample annotation
pData <- net$dds %>%
  colData %>%
  data.frame %>%
  mutate(STATUS = factor(STATUS))

# construct a trait matrix
trait_matrix <- model.matrix(~0 + STATUS,
                             data = pData) %>%
  set_colnames(levels(pData$STATUS))

# corrleate eigengenes with traits and calculate the p value
moduleTraitCor <- cor(MEs, trait_matrix)
moduleTraitPvalue <- corPvalueStudent(moduleTraitCor, nSamples)

# cluster the correlation matrix
order <- hclust(dist(moduleTraitCor))$order
moduleTraitCor <- moduleTraitCor[order,]
moduleTraitPvalue <- moduleTraitPvalue[rownames(moduleTraitCor),]

# prpare for heatmep construction
moduleTraitPvalue <- moduleTraitPvalue %>%
  data.frame(stringsAsFactors = FALSE) %>%
  mutate(module = str_replace(rownames(.), "ME", "")) %>%
  pivot_longer(!matches("module"))

moduleTraitCor <- moduleTraitCor %>%
  data.frame(stringsAsFactors = FALSE) %>%
  mutate(module = str_replace(rownames(.), "ME", "")) %>%
  pivot_longer(!matches("module"))

heatmap_data <- full_join(moduleTraitCor, moduleTraitPvalue, 
                      by = c("module", "name")) %>%
  mutate(label = paste(signif(value.x, 2), " (",
                       signif(value.y, 1), ")", sep = "")) %>%
  # select relevant columns
  dplyr::select(module, name, value.x, label) %>%
  
  # rename them accordingly
  dplyr::rename(Y = module, X = name, value = value.x) %>%
  mutate(X = factor(X, levels = c("normal", "diseased", "remission")),
         Y = factor(Y, levels = unique(Y))) 




# cluster the data
  
# generate the heatmap data - join module trait correlation and module trait pvalue, select proper columns and rename them accordingly.
heatmap <- ggplot(heatmap_data,
                  aes(x=X, 
                      y=Y, 
                      fill=value)) + 
  geom_tile() +
  geom_text(aes(label=label),
            size = 2.5,
            parse = TRUE) +
  scale_fill_gradient2(labels = unicode_minus,
                       low = "blue",
                       mid = "white",
                       high= "red",
                       limits = c(-1,1),
                       guide = guide_colorbar(label = TRUE,
                                              draw.ulim = TRUE, 
                                              draw.llim = TRUE,
                                              ticks = FALSE, 
                                              nbin = 10,
                                              label.position = "right",
                                              barwidth = 0.125,
                                              barheight = 3, 
                                              direction = "vertical")) +
  ylab("module") +
  xlab("") +
  labs(fill = "correlation") +
  md_theme_bw(base_size = base_size) +
  as_md_theme(theme(axis.ticks = element_blank(),
        axis.title.y = element_text(size = base_size),
        axis.text.x = element_text(angle = 90, 
                                   hjust = 1,
                                   size = base_size),
        axis.text.y = element_text(size = base_size),
        legend.title = element_text( size=10), 
        legend.text=element_text(size=10),
        legend.position="right"))
  # save the plot
heatmap %>%
  rio::export(here::here(plotsdir, paste("HeatmapPlot", accession, "RDS", sep=".")))

```


```{r determine_hubgenes}
library(tidyverse)
library(magrittr)
library(WGCNA)
library(Biobase)
library(DESeq2)
library(tidygraph)
library(igraph)
library(STRINGdb)
library(sccore)


# get the network and the data
accession <- "GSE128682"
net <- rio::import(here::here(datadir, paste(accession, "net", "RDS", sep = ".")),
                   trust = TRUE)

# define the palettes
palette_black <- RColorBrewer::brewer.pal(n = 8, name = "Greys") %>%
  colorRampPalette()
palette_red <- RColorBrewer::brewer.pal(n=8, name = "Reds") %>%
  colorRampPalette()

string_db <- STRINGdb$new(version="11", 
                          species=9606,
                          score_threshold=200, 
                          input_directory="")

moduleColors = paste("M", net$colors, sep = "")

genes <- data.frame(SYMBOL = colnames(net$params$datExpr),
                    MODULE = moduleColors) %>%
  filter(MODULE != "M0") %>%
  string_db$map("SYMBOL",
                removeUnmappedRows = TRUE) %>%
  group_by(STRING_id) %>%
  summarise(SYMBOL =paste(SYMBOL, collapse = ","), 
            MODULE = paste(MODULE, collapse = ",")) %>%
  ungroup()

ppi_probeid <- string_db$get_graph() %>%
  as_long_data_frame() %>%
  set_names(c("from", "to", "combined_score", "from_name", "to_name")) %>%
  inner_join(genes, by =c("from_name" = "STRING_id")) %>%
  select(-MODULE) %>%
  dplyr::rename(from_SYMBOL = SYMBOL) %>%
  inner_join(genes, by =c("to_name" = "STRING_id")) %>%
  select(-MODULE) %>%
  dplyr::rename(to_SYMBOL = SYMBOL) %>%
  select(-from, -to, -from_name, -to_name) %>%
  dplyr::rename(from = from_SYMBOL) %>%
  dplyr::rename(to = to_SYMBOL) %>%
  mutate(PPI = TRUE)

adjacency <- net$params$datExpr %>%
  WGCNA::adjacency(type = net$params$networkType,
                   power = net$params$power)

# construct a dataframe of Konnectivities from the adjacency

connectivity <-  adjacency %>%
  intramodularConnectivity(moduleColors) %>%
  rownames_to_column("name") %>%
  mutate(module = moduleColors) %>%
  group_by(module) %>%
  mutate(kWithin.norm = kWithin/max(kWithin)) %>%
  ungroup() %>%
  select(name, kTotal, kWithin, kWithin.norm, kOut, kDiff, module)

connectivity_list <- connectivity %>%
  dplyr::filter(module != "M0") %>%
  arrange(desc(kWithin.norm)) %>%
  tidyr::nest(gg = -"module") %>%
  deframe

connectivity_list %>%
  rio::export(here::here(resultsdir, paste0(accession, "_connectivity.xlsx")))

network <- adjacency %>%
  as_tbl_graph(directed = FALSE) %>%
  as_long_data_frame() %>%
  set_names(c("from", "to", "weight", "from_SYMBOL", "to_SYMBOL")) %>%
  dplyr::select(-from, -to) %>%
  dplyr::rename(from = from_SYMBOL) %>%
  dplyr::rename(to = to_SYMBOL) %>%
  left_join(ppi_probeid) %>%
  mutate(PPI = ifelse(is.na(PPI), FALSE, PPI)) %>%
  mutate(combined_score = ifelse(is.na(combined_score), 0, combined_score)) %>%
  mutate(COLOR = ifelse(PPI, 
                        val2col(weight, 
                                zlim = c(0,1), 
                                gradientPalette = palette_red(99)),
                        val2col(weight, 
                                zlim = c(0,1), 
                                gradientPalette = palette_black(99)))) %>%
  as_tbl_graph(directed = FALSE) %>%
  activate(nodes) %>%
  inner_join(connectivity)

network %>%
  rio::export(file.path(resultsdir, 
                        paste(accession, 
                              "network.RDS",
                          sep = ".")))

```


```{r druggable_genes}
library(tidyverse)
library(rDGIdb)
library(magrittr)
library(tidygraph)
library(rio)
# load the networks
network <- readRDS(file.path(resultsdir, paste(accession, "network.RDS", sep = ".")))

# extract hubgenes
genes <- network %>%
  activate(nodes) %>%
  data.frame %>%
  dplyr::select(module, name)

# query DGIdb
result <- genes$name %>%
  queryDGIdb() 

# Get DGIdb

interactions <- rio::import(here::here(datadir, "interactions.tsv"))
drugs <- rio::import(here::here(datadir, "drugs.tsv"))
categories <- rio::import(here::here(datadir, "categories.tsv"))

detailedResult <- interactions %>%
  dplyr::rename(name = gene_name) %>%
  inner_join(genes) %>%
  tidyr::nest(gg = -"module") %>%
  mutate_at(
    "gg",
    purrr::map,
    function(x) data.frame(x,stringsAsFactors = FALSE)
  ) %>%
  deframe() %>%
  .[order(names(.))] 

detailedResult %>%
  rio::export(here::here(resultsdir, "gene_drug_interactions.xlsx"))
```

